demotime/demotime/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.views import (
    login,
    logout_then_login,
    password_reset,
    password_reset_complete,
    password_reset_confirm,
    password_reset_done,
)

from demotime.views import (
    attachments,
    comments,
    events,
    files,
    groups,
    index_view,
    profile,
    projects,
    reviews,
    users,
    webhooks,
    gif_search,
)


# General
urlpatterns = [
    url('^$', index_view, name='index'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^terms-of-use/$', TemplateView.as_view(template_name='terms_of_use.html'), name='terms-of-use'),
    url(r'^privacy-policy/$', TemplateView.as_view(template_name='privacy_policy.html'), name='privacy-policy'),
    url(r'^help/$', TemplateView.as_view(template_name='demotime/help.html'), name='help'),
    url(r'^gifs/$', gif_search.GIFSearch.as_view(), name='gif-search'),
]

# Admin urls
urlpatterns += [
    url(r'^admin/groups/$', groups.group_list, name='group-list'),
    url(r'^admin/groups/create/$', groups.manage_group, name='group-manage'),
    url(r'^admin/groups/edit/(?P<group_slug>[\w-]+)/admins$', groups.manage_group_admins, name='group-manage-admins'),
    url(r'^admin/groups/edit/(?P<group_slug>[\w-]+)/$', groups.manage_group, name='group-manage'),
    url(r'^admin/group-types/create/$', groups.manage_group_type, name='group-type-manage'),
    url(r'^admin/group-types/edit/(?P<slug>[\w-]+)/$', groups.manage_group_type, name='group-type-manage'),
    url(r'^admin/projects/create/$', projects.project_admin, name='project-create'),
]

# Comments
urlpatterns += [
    url(
        r'^reviews/(?P<proj_slug>[\w-]+)/review/(?P<review_pk>[\d]+)/rev/(?P<rev_num>[\d]+)/comments/$',
        comments.comments_json_view,
        name='comments-api',
    ),
    url(
        r'^comment/(?P<comment_pk>[\d]+)/attachment/(?P<attachment_pk>[\d]+)/update/$',
        comments.delete_comment_attachment_view,
        name='update-comment-attachment'
    ),
]

# Attachments
urlpatterns += [
    url(
        r'^attachments/(?P<review_pk>[\d]+)/$',
        attachments.attachments_json_view, name='attachments-api'
    ),
    url(
        r'^attachments/(?P<review_pk>[\d]+)/(?P<attachment_pk>[\d]+)/$',
        attachments.attachments_json_view, name='attachments-api'
    ),
]

# Reviews
urlpatterns += [
    # Review Creation
    url(r'^reviews/(?P<proj_slug>[\w-]+)/create/$', reviews.create_review_view, name='create-review'),
    # DT-1234 redirect view
    url(r'^(?i)DT-(?P<pk>[\d]+)/$', reviews.dt_redirect_view, name='dt-redirect'),
    # Review Json Endpoint
    url(
        r'^reviews/(?P<proj_slug>[\w-]+)/review/(?P<pk>[\d]+)/json/$',
        reviews.review_json_view,
        name='review-json'
    ),
    # Review Detail Page
    url(
        r'^reviews/(?P<proj_slug>[\w-]+)/review/(?P<pk>[\d]+)/$',
        reviews.review_detail,
        name='review-detail'
    ),
    # Review Revision Detail Page
    url(
        r'^reviews/(?P<proj_slug>[\w-]+)/review/(?P<pk>[\d]+)/rev/(?P<rev_num>[\d]+)/$',
        reviews.review_detail,
        name='review-rev-detail'
    ),
    # Review Edit Page
    url(
        r'^reviews/(?P<proj_slug>[\w-]+)/review/(?P<pk>[\d]+)/edit/$',
        reviews.edit_review_form_view,
        name='edit-review'
    ),
    # Reviewer Approval/Rejection
    url(
        r'^reviews/(?P<proj_slug>[\w-]+)/review/(?P<review_pk>[\d]+)/reviewer-status/(?P<reviewer_pk>[\d]+)/$',
        reviews.reviewer_status_view,
        name='update-reviewer-status',
    ),
    # Review State Update (open/closed)
    url(
        r'^reviews/(?P<proj_slug>[\w-]+)/review/(?P<pk>[\d]+)/update-state/$',
        reviews.review_state_view,
        name='update-review-state'
    ),
    url(r'^reviews/list/$', reviews.review_list_view, name='review-list'),
    url(r'^reviews/search/$', reviews.review_search_json_view, name='reviews-search-json'),
    url(r'^reviews/(?P<proj_slug>[\w-]+)/search/$', reviews.review_search_json_view, name='reviews-search-json'),
    url(
        r'^reviews/(?P<proj_slug>[\w-]+)/review/(?P<review_pk>[\d]+)/attachment/(?P<attachment_pk>[\d]+)/update/$',
        reviews.delete_review_attachment_view,
        name='delete-review-attachment'
    ),
]

# Files
urlpatterns += [
    url(r'^file/profile/(?P<file_path>.+)$', files.user_profile_media_view, name='user-profile-media'),
    url(r'^file/(?P<pk>[\d]+)$', files.user_media_view, name='user-media'),
]

# Users
urlpatterns += [
    url(r'^accounts/login/$', login, name='login'),
    url(r'^accounts/logout/$', logout_then_login, name='logout'),
    url(r'^accounts/profile/(?P<pk>[\d]+)/$', profile.profile_view, name='profile'),
    url(r'^accounts/profile/(?P<pk>[\d]+)/edit/$', profile.edit_profile_view, name='edit-profile'),
    url(r'^accounts/profile/(?P<username>[\w.-_@]+)/edit/$', profile.edit_profile_view, name='edit-profile'),
    url(r'^(?i)accounts/profile/(?P<username>[\w.-_@]+)/$', profile.profile_view, name='profile'),
    url(
        r'^accounts/password/reset/$',
        password_reset,
        {
            'template_name': 'registration/password_reset_request.html',
            'post_reset_redirect': reverse_lazy('password_reset_done'),
        },
        name='password-reset'
    ),
    url(
        r'^accounts/password/reset/done/$',
        password_reset_done,
        {'template_name': 'registration/password_reset_submitted.html'},
        name='password_reset_done'
    ),
    url(
        r'^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        password_reset_confirm,
        {'template_name': 'registration/password_reset_confirmation.html'},
        name='password_reset_confirm'
    ),
    url(
        r'^accounts/password/reset/complete/$',
        password_reset_complete,
        {'template_name': 'registration/password_reset_completed.html'},
        name='password_reset_complete'
    ),
    url(r'^users/$', users.user_api, name='user-api'),
]

# Projects
urlpatterns += [
    url(r'projects/$', projects.project_json, name='project-json'),
    url(
        r'projects/(?P<proj_slug>[-\w]+)/events/$',
        events.EventView.as_view(),
        name='events'
    ),
    url(
        r'projects/(?P<proj_slug>[-\w]+)/admin/hooks/create/$',
        webhooks.manage_hooks,
        name='webhook-create'
    ),
    url(
        r'projects/(?P<proj_slug>[-\w]+)/admin/hooks/edit/(?P<hook_pk>[\d]+)/$',
        webhooks.manage_hooks,
        name='webhook-edit'
    ),
    url(
        r'projects/(?P<proj_slug>[-\w]+)/admin/settings/(?P<setting_pk>[\d]+)/$',
        projects.project_settings,
        name='project-settings-edit'
    ),
    url(r'projects/(?P<proj_slug>[-\w]+)/admin/edit/$', projects.project_admin, name='project-admin'),
    url(r'projects/(?P<proj_slug>[-\w]+)/admin/$', projects.project_detail, name='project-detail'),
    url(r'projects/(?P<proj_slug>[-\w]+)/$', projects.project_dashboard, name='project-dashboard'),

]

demotime/demotime/models/projects.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from demotime.models.base import BaseModel


class ProjectManager(models.Manager):

    def active(self):
        return self.get_queryset().filter(is_active=True)


class Project(BaseModel):

    name = models.CharField(max_length=128)
    slug = models.SlugField(unique=True)
    description = models.TextField(blank=True)
    groups = models.ManyToManyField('Group', through='ProjectGroup')
    members = models.ManyToManyField('auth.User', through='ProjectMember')
    is_public = models.BooleanField(default=False)
    token = models.CharField(max_length=256)
    is_active = models.BooleanField(default=True)

    objects = ProjectManager()

    def __str__(self):
        return 'Project {}'.format(self.name)

    def to_json(self):
        groups = []
        for group in ProjectGroup.objects.filter(project=self):
            groups.append(group.to_json())

        members = []
        for member in ProjectMember.objects.filter(project=self):
            members.append(member.to_json())

        return {
            'name': self.name,
            'slug': self.slug,
            'description': self.description,
            'groups': groups,
            'members': members,
            'is_public': self.is_public,
            'url': self.get_absolute_url(),
            'pk': self.pk,
            'created': self.created.isoformat(),
            'modified': self.modified.isoformat(),
        }

    def get_absolute_url(self):
        return reverse('project-detail', args=[self.slug])

    @property
    def project_members(self):
        return User.objects.filter(
            models.Q(projectmember__project=self) |
            models.Q(group__projectgroup__project=self)
        ).distinct().order_by('username')


class ProjectGroup(BaseModel):

    project = models.ForeignKey('Project')
    group = models.ForeignKey('Group')
    is_admin = models.BooleanField(default=False)

    def __str__(self):
        return 'ProjectGroup: {} - {}'.format(
            self.project.slug,
            self.group.slug
        )

    def to_json(self):
        return {
            'project_pk': self.project.pk,
            'group': self.group.to_json(),
            'is_admin': self.is_admin,
        }


class ProjectMember(BaseModel):

    project = models.ForeignKey('Project')
    user = models.ForeignKey('auth.User')
    is_admin = models.BooleanField(default=False)

    def __str__(self):
        return 'ProjectMember: {} - {}'.format(
            self.project.slug,
            self.user.userprofile.name,
        )

    def to_json(self):
        return {
            'project_pk': self.project.pk,
            'user_pk': self.user.pk,
            'username': self.user.username,
            'display_name': self.user.userprofile.name,
            'is_admin': self.is_admin,
        }

demotime/demotime/models/settings.py
import ast

from django.db import models
from django.conf import settings

from demotime.models.base import BaseModel


class SettingManager(models.Manager):

    def get_value(self, project, key, default=None):
        if not project:
            raise TypeError('Setting.objects.get_value requires a Project')

        try:
            obj = self.get(project=project, key=key)
        except self.model.DoesNotExist:
            if settings.DEBUG:
                raise
            else:
                return default
        else:
            return obj.value if obj.active else default


class Setting(BaseModel):

    # Setting Types
    LIST = 'list'
    BOOL = 'bool'
    DICT = 'dict'
    STRING = 'string'
    INT = 'int'

    # Setting Types Choices
    SWITCH_TYPES = (
        (LIST, 'List'),
        (BOOL, 'Boolean'),
        (DICT, 'Dictionary'),
        (STRING, 'String'),
        (INT, 'Integer'),
    )

    # Established Settings
    REMINDER_DAYS = 'reminder_days'
    EMOJIS_ENALBED = 'emojis_enabled'
    GIFS_ENABLED = 'gifs_enabled'

    # Settings without FKs to Project are 'system' Settings, and if they do have
    # a FK, they are an 'instance' of a 'system' setting for a project. This is
    # because the system defines the settings, and the Projects have independent
    # control of the setting within the project.
    project = models.ForeignKey('Project', null=True)
    title = models.CharField(max_length=128)
    key = models.SlugField(max_length=128, db_index=True)
    description = models.TextField(blank=True)
    raw_value = models.TextField()
    setting_type = models.CharField(
        max_length=32,
        choices=SWITCH_TYPES,
        db_index=True
    )
    active = models.BooleanField(default=False)

    objects = SettingManager()

    def __str__(self):
        return 'Setting: {}'.format(self.title)

    @classmethod
    def create_setting(cls, title, key, raw_value, setting_type,
                       project, description='', active=False):
        return cls.objects.create(
            title=title,
            key=key,
            description=description,
            raw_value=raw_value,
            setting_type=setting_type,
            active=active,
            project=project,
        )

    def _value_dict(self):
        return ast.literal_eval(self.raw_value)

    def _value_list(self):
        if self.raw_value.startswith('[') and self.raw_value.endswith(']'):
            return tuple(ast.literal_eval(self.raw_value))
        else:
            values = self.raw_value.split(',')
            return tuple(v.strip() for v in values)

    def _value_bool(self):
        if self.raw_value.lower() in ('true', 't', '1'):
            return True

        return False

    def _value_int(self):
        return int(self.raw_value)

    @property
    def value(self):
        if not self.active:
            return False

        if self.setting_type == self.DICT:
            return self._value_dict()
        elif self.setting_type == self.LIST:
            return self._value_list()
        elif self.setting_type == self.BOOL:
            return self._value_bool()
        elif self.setting_type == self.INT:
            return self._value_int()

        # Strings
        return self.raw_value

    class Meta:
        index_together = [
            ('project', 'key'),
        ]

demotime/demotime/views/profile.py
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import DetailView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from demotime import forms, models


class EditProfileView(DetailView):

    model = models.UserProfile
    template_name = 'demotime/edit_profile.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.profile_form = None
        self.lookup_kwargs = kwargs
        return super(EditProfileView, self).dispatch(request, *args, **kwargs)

    def init_profile_form(self, data=None, files=None):
        profile = self.request.user.userprofile
        kwargs = {
            'instance': profile,
            'initial': {
                'email': self.request.user.email,
                'bio': profile.bio,
                'display_name': profile.display_name,
            },
        }
        if data:
            kwargs['data'] = data
        if files:
            kwargs['files'] = files
        return forms.UserProfileForm(**kwargs)

    def get_object(self, *args, **kwargs):
        lookup_dict = {'user': self.request.user}
        if self.lookup_kwargs.get('pk'):
            lookup_dict['pk'] = self.lookup_kwargs['pk']
        if self.lookup_kwargs.get('username'):
            lookup_dict['user__username'] = self.lookup_kwargs['username']

        return get_object_or_404(
            models.UserProfile,
            **lookup_dict
        )

    def get_context_data(self, *args, **kwargs):
        context = super(EditProfileView, self).get_context_data(*args, **kwargs)
        if not self.profile_form:
            self.profile_form = self.init_profile_form()

        context['profile_form'] = self.profile_form
        return context

    def post(self, request, *args, **kwargs):
        self.profile_form = self.init_profile_form(data=request.POST, files=request.FILES)
        if self.profile_form.is_valid() and request.user == self.get_object().user:
            profile = self.request.user.userprofile
            user = profile.user
            data = self.profile_form.cleaned_data
            if data.get('avatar'):
                # If they didn't upload anything, we'll keep what we have,
                # otherwise we set it
                profile.avatar = data['avatar']
            if data.get('password_one'):
                user.set_password(data.get('password_one'))

            user.email = data.get('email')
            profile.bio = data.get('bio')
            profile.display_name = data.get('display_name')
            profile.save()
            user.save()
            return redirect('profile', pk=profile.pk)
        else:
            return self.get(request, *args, **kwargs)


class ProfileView(DetailView):

    model = models.UserProfile
    template_name = 'demotime/profile.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.profile_form = None
        self.lookup_args = kwargs
        return super(ProfileView, self).dispatch(request, *args, **kwargs)

    def get_object(self, *args, **kwargs):
        lookup_dict = {}
        if self.lookup_args.get('pk'):
            lookup_dict['pk'] = self.lookup_args['pk']
        if self.lookup_args.get('username'):
            lookup_dict['user__username'] = self.lookup_args['username'].lower()

        return get_object_or_404(
            models.UserProfile,
            **lookup_dict
        )

    def get_context_data(self, *args, **kwargs):
        context = super(ProfileView, self).get_context_data(*args, **kwargs)
        obj = self.get_object()
        context['open_demos'] = models.Review.objects.filter(
            creator__user=obj.user,
            creator__active=True,
            state=models.reviews.OPEN,
        )
        context['open_reviews'] = models.Review.objects.filter(
            reviewers=obj.user,
            state=models.reviews.OPEN
        )
        context['followed_demos'] = models.Review.objects.filter(
            followers=obj.user,
            state=models.reviews.OPEN,
        )
        owner_viewing = self.request.user == obj.user
        context['owner_viewing'] = owner_viewing
        return context


profile_view = ProfileView.as_view()
edit_profile_view = EditProfileView.as_view()

demotime/demotime/templates/demotime/edit_comment.html
{# this file has been deprecated #}

demotime/demotime/templates/demotime/edit_review.html
{% extends 'layout-user.html' %}

{% block sub_nav %}{% endblock %}

{% block title %} - Updating DT-{{ review_inst.pk }}{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
    <div class="container">
        <a href="{% url 'index' %}">Your dashboard</a> &gt;
        <a href="{% url 'project-dashboard' project.slug %}">{{ project.name }}</a> &gt;
        <a href="{{ review_inst.get_absolute_url }}">DT-{{ review_inst.pk }}</a>
            {% if review_inst.title %}
                - {{ review_inst.title }}
            {% endif %}
            &gt;
        {% if review_inst.reviewrevision_set.all|length > 1 %}
            New revision
        {% else %}
            Edit details
        {% endif %}
    </div>
</div>
{% endblock %}

{% block styles %}
{{ block.super }}
<style>
.review {
    font-size: 12px;
}
a.error {
    transition:5s;
}
h1 em {
    font-style: normal;
    font-size: 20px;
    vertical-align: middle;
    color: #999;
}
.review h3 {
    font-size:1.1em;
    font-weight:400;
}
.review select {
    margin-bottom:2em;
}
.form-group.first {
    margin-top: 0;
}
.attachments {
    margin-top: 20px;
}
.current_attachments .demobox {
    margin-bottom: 10px;
}
@media screen and (max-width:680px) {
    h3 small {
        display: block;
        font-size: 11px;
    }
}
.form-buttons {
    margin-top: 60px;
}
</style>
{% endblock %}

{% block content %}
<h1>DT-{{ review_inst.pk }}{% if review_inst.state == "draft"%} (Draft){% endif %}</h1>
<article>
    <section>
        <div class="review">
            <form action="" method="post" enctype="multipart/form-data" id="submit_review" novalidate>
                {% csrf_token %}
                <div class="form-group" style="margin-top: 0">
                    <h3 class="icon icon-lightbulb">
                        {{ review_form.title.label }}
                        <small>ex. "TP #1234: Destroyed Tetsuo as his power grew out of control"</small>
                    </h3>
                    {{ review_form.title.errors }}
                    {{ review_form.title }}
                    <script>
                        $('.id_title').focus();
                    </script>
                </div>
                <div class="form-group">
                    <h3 class="icon icon-link-ext">
                        {{ review_form.case_link.label }}
                        <small>ex. https://someproject.taskmanager.com/entity/1234</small>
                    </h3>
                    {{ review_form.case_link.errors }}
                    {{ review_form.case_link }}
                </div>
                <div class="form-group">
                    <h3 class="icon icon-pencil" id="demo-description">
                        {% if review_inst.state != "draft" %}
                            Revision description
                            <small>Give your revision some context</small>
                        {% else %}
                            Demo description
                            <small>A general description of what the demo is about &mdash; this gives your attachments some context</small>
                        {% endif %}
                    </h3>
                    {{ review_form.description.errors }}
                    {{ review_form.description }}
                </div>
                <article>
                    {% if review_inst.revision.attachments.exists %}
                        <h3 class="icon icon-attach">
                            Current attachments
                            <span class="help" title="By default, your existing attachments
                            carry over to your new revision. If you'd like to remove one or more
                            attachments from your demo, you can click the small 'delete' link next
                            to the appropriate demo below."></span>
                            <small>Remove attachments you would prefer not appear in the next revision</small>
                        </h3>
                        <section class="attachments" style="margin-bottom: 40px">
                            {% for attachment in review_inst.revision.attachments.all %}
                                {% include "includes/review_attachment.html" with project=project review_inst=review_inst attachment=attachment show_remove=True %}
                            {% endfor %}
                        </section>
                        <div style="display: none">{{ review_form.delete_attachments.label }}{{ review_form.delete_attachments }}</div>
                    {% endif %}
                    <div class="attachments">
                        <h3 class="icon icon-attach">Add attachments <small>Document your demo with screenshots, videos, documents &mdash; anything</small></h3>
                        {{ attachment_forms.management_form }}
                        {% for form in attachment_forms %}
                            <section{% if forloop.counter > 1 %} style="display:none"{% endif %}>
                                {% include "includes/attachments_form.html" with form=form %}
                                {{ form.attachment.errors }}
                            </section>
                        {% endfor %}
                    </div>
                </article>
                <div class="form-group">
                    <div class="creators">
                        <h3 class="icon icon-pencil">
                            Demo co-owner
                            <span class="help" title="Sometimes you might want to team-up on a demo with a fellow
                            colleague. Adding a co-owner essentially makes that person an administrator of the demo.
                            They will be notified that they have been added to the demo as a co-owner and can then also
                            add attachments, create revisions and so forth."></span>
                            <small>invite someone to also update the contents of this demo (optional)</small>
                        </h3>
                        <section>
                            {{ review_form.creators.errors }}
                            {{ review_form.creators }}
                        </section>
                    </div>
                </div>
                <div class="form-group" style="margin-top: 60px">
                    <h3 class="icon icon-user">
                        Reviewers and Followers
                        <span class="help" title="When you assign someone as a 'reviewer' they
                        will need to either approve or reject a demo. A follower can simply follow
                        the progress of a demo without the ability or need to approve or reject."></span>
                        <small>Hold down 'cmd' to select multiple people</small>
                    </h3>
                    <div class="split~680 by:2 with-gap:3">
                        <div class="cel">
                            <div class="form-group">
                                <h3>
                                    {{ review_form.reviewers.label }}
                                    <small>must approve your demo</small>
                                </h3>
                                {{ review_form.reviewers.errors }}
                                {{ review_form.reviewers }}
                            </div>
                        </div>
                        <div class="cel">
                            <div class="form-group">
                                <h3>
                                    {{ review_form.followers.label }}
                                    <small>simply along for the ride</small>
                                </h3>
                                {{ review_form.followers.errors }}
                                {{ review_form.followers }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <section>
                        <label>
                            {{ review_form.is_public }} Make demo <strong>public</strong>
                            <span class="help" title="Public demos can be viewed by anyone outside of
                            DemoTime."></span>
                        </label>
                        <div>{{ review_form.is_public.errors }}</div>
                    </section>
                </div>
                {{ review_form.state }}
                {{ review_form.trash }}
                {% if review_inst.reviewrevision_set.all|length > 1 %}
                    <section>
                        <strong>Heads up!</strong> Adding a revision to your demo will
                        reset everyone's approval status back to 'Reviewing'
                    </section>
                {% endif %}
                <div class="form-group form-buttons">
                    <div class="split by:2">
                        <div class="cel">
                            <button id="create-demo"
                                onclick="$('#id_state').val('open')"
                                class="button-confirm"
                                type="submit">
                                {% if review_inst.state == "draft" %}
                                    Publish Demo
                                {% else %}
                                    Update demo
                                {% endif %}
                            </button>
                        </div>
                        <div class="cel right">
                            {% if review_inst.pk %}
                                {% if review_inst.state == 'draft' %}
                                    <button id="save-draft"
                                        class="button-emphasized"
                                        onclick="$('#id_state').val('draft')"
                                        type="submit">
                                        Save
                                    </button>
                                    <button id="delete-draft"
                                        class="button-alert"
                                        onclick="$('#id_trash').val(true)"
                                        type="submit">
                                        Delete
                                    </button>
                                {% endif %}
                            {% else %}
                                <button id="save-draft"
                                    class="button-emphasized"
                                    onclick="$('#id_state').val('draft')"
                                    type="submit">
                                    Save Draft
                                </button>
                            {% endif %}
                            <button type="button"
                                class="button-clear"
                                onclick="javascript: history.go(-1)">
                                Cancel
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>
</article>
{% endblock %}

{% block scripts %}
{{ block.super }}
<script src="/static/scripts/review_utils.js?{{ site_settings.CACHE_BUSTER }}"></script>
{% endblock %}

demotime/demotime/templates/demotime/project_settings.html
{% extends 'layout-user.html' %}
{% block title %}Project {{ object.name }} Administration{% endblock %}

{% block sub_nav_contents %}
    <a href="javascript:history.back()" class="subnav-item">Cancel</a></li>
{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
    <div class="container">
        <a href="{% url 'index' %}">Your dashboard</a> &gt;
            Edit Setting - {{ setting.title }}
    </div>
</div>
{% endblock %}

{% block styles %}
{{ block.super }}
<style>
a.error {
    transition:5s;
}
.project h3 {
    font-size:1.1em;
    font-weight:400;
}
.project {
    font-size: 12px;
}
.form-group.first {
    margin-top: 0;
}
.project label {
    font-size: 1.7em;
    color: #555;
    font-weight: 400;
}

</style>
{% endblock %}

{% block content %}
<h1>Edit Setting - {{ setting.title }}

<article class="project">
    <section>
        <form action="{% url 'project-settings-edit' project.slug setting.pk %}" method='post'>
            {% csrf_token %}
            <h3 class="icon icon-pencil">
                Setting Information:
            </h3>
            <ul>
                <li>Description: {{ setting.description }}</li>
                <li>Setting Type: {{ setting.get_setting_type_display }}</li>
            </ul>
            <section>
                {{ form.as_p }}
            </section>
            <button type="button" onclick="javascript: history.go(-1)">Cancel</button>
            <button type="submit">Submit</button>
        </form>
    </section>
</article>
{% endblock %}